spring:
  datasource:
    url: jdbc:mysql://localhost:3306/amovie?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      file-size-threshold: 1000MB
thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  cache: false

mybatis:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.etc.amovie.entity

pagehelper:
  reasonable: true

filepath: D:\my_document\upload
server:
  port: 8112